# This policy opens port 53 and 5353 for DNS,
# port 2049 for communication with NFS file servers, ports 443 and 3260
# for communication to block storage, port 10250 for VPN communication,
# and port 2040 and 2041 on 172.20.0.0 for the master API server local proxy. It also
# allows pod access to other pods, denies access to private networks but allows access to
# public networks, and allows access in each zone of the region to the master.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-egress-pods-private
spec:
  egress:
  - action: Allow
    destination:
      ports:
      - 53
      - 5353
      - 443
      - 2049
      - 3260
      - 10250
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
      - 5353
      - 443
      - 2049
      - 3260
      - 10250
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      ports:
      - 2040:2041
      nets:
      - 172.20.0.0/24
    protocol: UDP
  - action: Allow
    destination:
      ports:
      - 2040:2041
      nets:
      - 172.20.0.0/24
    protocol: TCP
  - action: Allow
    destination:
      selector: projectcalico.org/orchestrator == 'k8s'
    source: {}
  # Denies pod egress to private networks. If workers are connected to a public VLAN,
  # pod egress is permitted to public networks.
  - action: Allow
    destination:
      notNets:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for EU Central: ams03, mil01, osl01, par01, fra02, fra04, fra05
      - 166.9.28.107/32
      - 166.9.28.17/32
      - 166.9.28.19/32
      - 166.9.28.20/32
      - 166.9.28.22/32
      - 166.9.28.23/32
      - 166.9.28.24/32
      - 166.9.28.43/32
      - 166.9.28.59/32
      - 166.9.28.92/32
      - 166.9.28.94/32
      - 166.9.28.95/32
      - 166.9.30.100/32
      - 166.9.30.11/32
      - 166.9.30.12/32
      - 166.9.30.13/32
      - 166.9.30.22/32
      - 166.9.30.43/32
      - 166.9.30.55/32
      - 166.9.30.56/32
      - 166.9.32.20/32
      - 166.9.32.26/32
      - 166.9.32.27/32
      - 166.9.32.28/32
      - 166.9.32.45/32
      - 166.9.32.53/32
      - 166.9.32.56/32
      - 166.9.32.8/32
      - 166.9.32.88/32
      - 166.9.32.9/32
      ports:
      - 20000:32767
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for EU Central: ams03, mil01, osl01, par01, fra02, fra04, fra05
      - 166.9.28.107/32
      - 166.9.28.17/32
      - 166.9.28.19/32
      - 166.9.28.20/32
      - 166.9.28.22/32
      - 166.9.28.23/32
      - 166.9.28.24/32
      - 166.9.28.43/32
      - 166.9.28.59/32
      - 166.9.28.92/32
      - 166.9.28.94/32
      - 166.9.28.95/32
      - 166.9.30.100/32
      - 166.9.30.11/32
      - 166.9.30.12/32
      - 166.9.30.13/32
      - 166.9.30.22/32
      - 166.9.30.43/32
      - 166.9.30.55/32
      - 166.9.30.56/32
      - 166.9.32.20/32
      - 166.9.32.26/32
      - 166.9.32.27/32
      - 166.9.32.28/32
      - 166.9.32.45/32
      - 166.9.32.53/32
      - 166.9.32.56/32
      - 166.9.32.8/32
      - 166.9.32.88/32
      - 166.9.32.9/32
      ports:
      - 20000:32767
    protocol: TCP
    source: {}
  order: 1500
  selector: projectcalico.org/orchestrator == 'k8s'
  types:
  - Egress
