apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmliberty-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ibmliberty
  template:
    metadata:
      labels:
        app: ibmliberty
    spec:
      containers:
      - name: ibmliberty
        image: icr.io/ibmliberty
