# This policy allows outgoing network traffic from pods to other IBM Cloud services.
# The example nets in this policy are for IBM Cloud Container Registry
# and IBM Cloud Monitoring with Sysdig.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-services-pods
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 169.60.98.80/29
      - 169.62.37.240/29
      - 169.63.104.232/29
      # IBM Cloud Container Registry: AP South nets for your own registry
      - 168.1.1.240/29
      - 130.198.88.128/29
      - 135.90.66.48/29
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: AU Syd nets
      - 130.198.80.155/32
      - 135.90.73.100/32
      - 168.1.213.78/32
      ports:
      - 6443
    protocol: TCP
    source: {}
  order: 1800
  selector: projectcalico.org/orchestrator == 'k8s'
  types:
  - Egress
